---
name: Norminette Check

on:
  push:

jobs:
  norminette-check:
    runs-on: ubuntu-latest
    name: "Norminette Check"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - run: python3 -m pip install --break-system-packages -U norminette
      - run: |
          if [ -n "$(norminette -RCheckForbiddenSourceHeader 2>&1 | grep 'Error:')" ]; then
              echo "Error 1"
              exit 1
          else
              echo "Error 2"
              exit 0
          fi
