---
name: Norminette Check

on:
  push:

jobs:
  norminette-check:
    runs-on: ubuntu-latest
    name: "Norminette Check"

    steps:
      - name: Checkout user code
        uses: actions/checkout@v3

      - name: Install Python3
        uses: actions/setup-python@v4
        with:
            python-version: "3.10"

      - name: Install Norminette using pip
        run: |
            python3 -m pip install -U norminette

      - name: Execute Norminette
        run: |
            output=$(norminette -RCheckForbiddenSourceHeader 2>&1 | grep "Error:")
            if [ -n "$output" ]; then
                echo "Norm Error"
                exit 1
            fi